#!/usr/bin/env bash
# zephyrcode installer — one command to get the `zephyrcode` coding agent on your
# PATH, configured and ready. Mirrors the Claude Code install model: build, drop a
# launcher into ~/.local/bin, wire up PATH, and write the API key once.
#
#   ./install.sh
#
# Honors env: DEEPSEEK_API_KEY (skips the prompt), ZEPHYRCODE_HOME, ZEPHYRCODE_BIN_DIR.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${ZEPHYRCODE_BIN_DIR:-$HOME/.local/bin}"
HOME_DIR="${ZEPHYRCODE_HOME:-$HOME/.zephyrcode}"
LAUNCHER="$BIN_DIR/zephyrcode"
BUNDLE="$REPO_DIR/packages/cli/dist/zephyrcode.js"

say()  { printf '\033[33m▸\033[0m %s\n' "$1"; }
ok()   { printf '\033[32m✔\033[0m %s\n' "$1"; }
die()  { printf '\033[31m✘ %s\033[0m\n' "$1" >&2; exit 1; }

# 1. Prerequisites: Node >= 20 and pnpm.
command -v node >/dev/null 2>&1 || die "Node.js >= 20 is required (not found). Install it, then re-run."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "Node.js >= 20 required (found $(node -v))."

if ! command -v pnpm >/dev/null 2>&1; then
  if command -v corepack >/dev/null 2>&1; then
    corepack enable >/dev/null 2>&1 || true
  fi
  command -v pnpm >/dev/null 2>&1 || die "pnpm is required. Install it: npm install -g pnpm"
fi

# 2. Install deps + build the single-file bundle.
say "Installing dependencies…"
(cd "$REPO_DIR" && pnpm install --silent)
say "Building zephyrcode…"
(cd "$REPO_DIR" && pnpm --filter @coding-agent/cli build >/dev/null)
[ -f "$BUNDLE" ] || die "Build did not produce $BUNDLE"

# 3. Config dir + API key (written once; auto-configures the environment).
mkdir -p "$HOME_DIR"
ENV_FILE="$HOME_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  KEY="${DEEPSEEK_API_KEY:-}"
  if [ -z "$KEY" ] && [ -t 0 ]; then
    printf 'Enter your DeepSeek API key (blank = offline stub model): '
    read -r KEY
  fi
  umask 077
  cat > "$ENV_FILE" <<EOF
# zephyrcode config (written by install.sh)
DEEPSEEK_API_KEY=${KEY}
DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-v4-pro}
DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
EOF
  ok "Wrote config → $ENV_FILE"
else
  say "Keeping existing config → $ENV_FILE"
fi

# 4. Launcher on PATH. Handles `zephyrcode --update` itself (it knows the repo).
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# zephyrcode launcher (generated by install.sh — do not edit)
ZEPHYRCODE_REPO="$REPO_DIR"
if [ "\${1:-}" = "--update" ]; then
  cd "\$ZEPHYRCODE_REPO" || exit 1
  git pull --ff-only 2>/dev/null || true
  pnpm install --silent && pnpm --filter @coding-agent/cli build >/dev/null \\
    && printf '\033[32m✔\033[0m zephyrcode updated.\n'
  exit \$?
fi
exec node "\$ZEPHYRCODE_REPO/packages/cli/dist/zephyrcode.js" "\$@"
EOF
chmod +x "$LAUNCHER"
ok "Installed launcher → $LAUNCHER"

# 5. Ensure BIN_DIR is on PATH.
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    RC=""
    case "${SHELL:-}" in
      *zsh)  RC="$HOME/.zshrc" ;;
      *bash) RC="$HOME/.bashrc" ;;
    esac
    LINE="export PATH=\"$BIN_DIR:\$PATH\""
    if [ -n "$RC" ]; then
      if ! grep -qF "$BIN_DIR" "$RC" 2>/dev/null; then
        printf '\n# Added by zephyrcode install.sh\n%s\n' "$LINE" >> "$RC"
      fi
      say "Added $BIN_DIR to PATH in $RC — restart your shell or run: source $RC"
    else
      say "Add this to your shell profile: $LINE"
    fi
    ;;
esac

printf '\n'
ok "zephyrcode installed."
printf '   Start it:   \033[1mzephyrcode\033[0m\n'
printf '   Options:    \033[1mzephyrcode --help\033[0m\n'
printf '   Update it:  \033[1mzephyrcode --update\033[0m\n'
