# blazecoder installer for Windows — PowerShell equivalent of install.sh
# Usage: .\install.ps1
# Honors env: DEEPSEEK_API_KEY (sets the key non-interactively), BLAZECODER_HOME, BLAZECODER_BIN_DIR

$ErrorActionPreference = "Stop"

$REPO_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$BIN_DIR  = if ($env:BLAZECODER_BIN_DIR) { $env:BLAZECODER_BIN_DIR } else { "$env:USERPROFILE\.local\bin" }
$HOME_DIR = if ($env:BLAZECODER_HOME)    { $env:BLAZECODER_HOME }    else { "$env:USERPROFILE\.blazecoder" }
$LAUNCHER = Join-Path $BIN_DIR "blazecoder.cmd"
$BUNDLE   = Join-Path $REPO_DIR "packages\cli\dist\blazecoder.js"

function Say  { param($msg) Write-Host "▸ $msg" -ForegroundColor Yellow }
function Ok   { param($msg) Write-Host "✔ $msg" -ForegroundColor Green  }
function Die  { param($msg) Write-Host "✘ $msg" -ForegroundColor Red; exit 1 }

# 1. Prerequisites: Node >= 20 and pnpm.
try { $null = Get-Command node -ErrorAction Stop } catch { Die "Node.js >= 20 is required (not found). Install it from https://nodejs.org, then re-run." }

$nodeMajor = [int](node -p "process.versions.node.split('.')[0]")
if ($nodeMajor -lt 20) { Die "Node.js >= 20 required (found $(node -v))." }

$hasPnpm = $null -ne (Get-Command pnpm -ErrorAction SilentlyContinue)
if (-not $hasPnpm) {
    $hasCorepack = $null -ne (Get-Command corepack -ErrorAction SilentlyContinue)
    if ($hasCorepack) {
        try { corepack enable 2>$null } catch {}
        $hasPnpm = $null -ne (Get-Command pnpm -ErrorAction SilentlyContinue)
    }
    if (-not $hasPnpm) { Die "pnpm is required. Install it: npm install -g pnpm" }
}

# 2. Install deps + build the single-file bundle.
Say "Installing dependencies..."
Push-Location $REPO_DIR
try {
    pnpm install --silent
    if ($LASTEXITCODE -ne 0) { Die "pnpm install failed." }

    Say "Building blazecoder..."
    pnpm --filter "@blazecoder/cli" build | Out-Null
    if ($LASTEXITCODE -ne 0) { Die "CLI build failed." }
    if (-not (Test-Path $BUNDLE)) { Die "Build did not produce $BUNDLE" }

    # Desktop GUI — best-effort.
    Say "Building the desktop GUI..."
    $desktopBuilt = $false
    try {
        pnpm --filter "@blazecoder/desktop" build 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) { $desktopBuilt = $true }
    } catch {}
    if ($desktopBuilt) {
        Ok "Desktop GUI built (launch with 'blazecoder --gui')."
    } else {
        Say "Desktop GUI build skipped — 'blazecoder --gui' will build it on first use."
    }
} finally {
    Pop-Location
}

# 3. Connect a model (onboarding).
if (-not (Test-Path $HOME_DIR)) { New-Item -ItemType Directory -Force $HOME_DIR | Out-Null }
$CONFIG_FILE = Join-Path $HOME_DIR "config.json"
if (Test-Path $CONFIG_FILE) {
    Say "Keeping existing config -> $CONFIG_FILE"
} elseif ([Console]::IsInputRedirected -eq $false -or $env:DEEPSEEK_API_KEY) {
    Say "Connecting a model..."
    $env:BLAZECODER_HOME = $HOME_DIR
    node $BUNDLE --setup
    if ($LASTEXITCODE -ne 0) { Say "Setup skipped — run 'blazecoder --setup' anytime." }
} else {
    Say "No terminal for setup; run 'blazecoder --setup' (or just 'blazecoder') to connect a model."
}

# 4. Launcher on PATH.
if (-not (Test-Path $BIN_DIR)) { New-Item -ItemType Directory -Force $BIN_DIR | Out-Null }
@"
@echo off
rem blazecoder launcher (generated by install.ps1 -- do not edit)
set BLAZECODER_REPO=$REPO_DIR
if not "%~1"=="--update" goto run
cd /d "%BLAZECODER_REPO%"
if errorlevel 1 (
  echo blazecoder repo not found at %BLAZECODER_REPO% [re-run install.ps1]
  exit /b 1
)
git pull --ff-only 2>nul
if errorlevel 1 echo git pull did not update [offline or non-fast-forward]; rebuilding current checkout.
call pnpm install --silent
if errorlevel 1 exit /b %ERRORLEVEL%
call pnpm --filter "@blazecoder/cli" build >nul
if errorlevel 1 exit /b %ERRORLEVEL%
call pnpm --filter "@blazecoder/desktop" build >nul 2>&1
echo blazecoder rebuilt.
exit /b 0
:run
node "%BLAZECODER_REPO%\packages\cli\dist\blazecoder.js" %*
"@ | Set-Content -Encoding ascii $LAUNCHER
Ok "Installed launcher -> $LAUNCHER"

# 5. Ensure BIN_DIR is on PATH (user-scope, persistent).
$userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User")
if ($userPath -notlike "*$BIN_DIR*") {
    $newPath = "$BIN_DIR;$userPath"
    [System.Environment]::SetEnvironmentVariable("PATH", $newPath, "User")
    Say "Added $BIN_DIR to your user PATH. Restart your terminal (or open a new PowerShell window) for it to take effect."
} else {
    Say "$BIN_DIR is already on your PATH."
}

Write-Host ""
Ok "blazecoder installed."
Write-Host "   Start it:    " -NoNewline; Write-Host "blazecoder" -ForegroundColor White -NoNewline; Write-Host " (new terminal)"
Write-Host "   Desktop GUI: " -NoNewline; Write-Host "blazecoder --gui" -ForegroundColor White
Write-Host "   Connect key: " -NoNewline; Write-Host "blazecoder --setup" -ForegroundColor White
Write-Host "   Options:     " -NoNewline; Write-Host "blazecoder --help" -ForegroundColor White
Write-Host "   Update it:   " -NoNewline; Write-Host "blazecoder --update" -ForegroundColor White
