/**
 * Client-side project export (salvaged from V1). The frontend accumulates the
 * file graph from file_change events, so exporting a runnable zip is a pure
 * client action — no backend round-trip.
 */

import JSZip from "jszip";
import type { UiFile } from "./agentState";

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "project";
}

export async function exportProjectZip(name: string, files: UiFile[]): Promise<void> {
  const zip = new JSZip();
  const root = slug(name);
  for (const file of files) {
    zip.file(`${root}${file.path}`, file.content);
  }
  zip.file(
    `${root}/README.md`,
    `# ${name}\n\nGenerated by the coding agent.\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  );
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${root}.zip`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
